import { useEffect, useMemo, useState } from 'react';
import { Check, BriefcaseBusiness, Mail, UserRound } from 'lucide-react';
import toast from 'react-hot-toast';
import useAuthStore from '../store/authStore';
import useApplicationStore from '../store/applicationStore';
import { emailPattern } from '../utils/validation';

const Profile = () => {
  const { user, fetchUser, updateProfile } = useAuthStore(); const { applications, fetchApplications } = useApplicationStore();
  const [form, setForm] = useState({ name: '', email: '' }); const [errors, setErrors] = useState({}); const [saving, setSaving] = useState(false);
  useEffect(() => { fetchUser(); fetchApplications(); }, []); useEffect(() => { if (user) setForm({ name: user.name || '', email: user.email || '' }); }, [user]);
  const stats = useMemo(() => ({ total: applications.length, interviews: applications.filter((app) => app.status === 'Interview').length, offers: applications.filter((app) => app.status === 'Offer').length }), [applications]);
  const save = async (event) => { event.preventDefault(); const next = {}; if (form.name.trim().length < 2) next.name = 'Enter at least 2 characters.'; if (!emailPattern.test(form.email.trim())) next.email = 'Enter a valid email address.'; if (Object.keys(next).length) return setErrors(next); setSaving(true); try { await updateProfile({ name: form.name.trim(), email: form.email.trim() }); toast.success('Profile updated'); } catch (error) { toast.error(error.message); } finally { setSaving(false); } };
  const initials = user?.name?.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'U';
  const statCards = [[stats.total, 'Applications tracked', 'Your full pipeline', BriefcaseBusiness], [stats.interviews, 'Interviews in motion', 'Conversations to prepare for', UserRound], [stats.offers, 'Offers received', 'Proof that things are moving', Check]];
  return <div className="max-w-[1450px] mx-auto"><div className="mb-9"><h1 className="app-page-title">Profile & settings</h1><p className="app-subtitle">Keep your workspace personal and up to date.</p></div><div className="grid grid-cols-1 xl:grid-cols-12 gap-5"><section className="xl:col-span-8 glass rounded-2xl p-8"><div className="flex gap-5 items-center pb-7 border-b border-[#eaded8]"><div className="w-18 h-18 min-w-18 rounded-3xl bg-[#3d887b] text-white flex items-center justify-center text-xl font-bold p-4">{initials}</div><div><h2 className="text-xl font-semibold text-[#29424c]">Personal details</h2><p className="text-[#718792] mt-1">This is how CareerMatrix greets you each morning.</p></div></div><form onSubmit={save} noValidate className="mt-7 space-y-5"><label className="block text-sm font-semibold text-[#29424c]">Full name *<input value={form.name} onChange={(e) => { setForm({ ...form, name: e.target.value }); setErrors({ ...errors, name: '' }); }} className="mt-2 w-full rounded-xl border border-[#dfd0c8] bg-white px-4 py-3 outline-none focus:border-[#3d887b]"/>{errors.name && <span className="text-xs text-red-500 mt-1 block">{errors.name}</span>}</label><label className="block text-sm font-semibold text-[#29424c]">Email address *<input type="email" value={form.email} onChange={(e) => { setForm({ ...form, email: e.target.value }); setErrors({ ...errors, email: '' }); }} className="mt-2 w-full rounded-xl border border-[#dfd0c8] bg-white px-4 py-3 outline-none focus:border-[#3d887b]"/>{errors.email && <span className="text-xs text-red-500 mt-1 block">{errors.email}</span>}</label><div className="pt-6 border-t border-[#eaded8] flex justify-end"><button disabled={saving} className="app-button rounded-xl px-5 py-3 font-semibold text-sm flex items-center gap-2"><Check className="w-4 h-4"/>{saving ? 'Saving…' : 'Save changes'}</button></div></form></section><aside className="xl:col-span-4 space-y-4">{statCards.map(([value, label, caption, Icon]) => <div key={label} className="glass rounded-2xl p-6"><Icon className="w-5 h-5 text-[#3d887b]"/><p className="text-sm text-[#718792] mt-5">{label}</p><p className="text-4xl font-semibold tracking-tight text-[#29424c] mt-2">{value}</p><p className="text-sm text-[#3d887b] font-semibold mt-3">{caption}</p></div>)}</aside></div></div>;
};
export default Profile;
